// Icon names shared by the navigation model (tabs.ts) and the renderer's
// registry, so a misspelt icon fails typecheck instead of rendering nothing.
export const ICON_NAMES = [
  'convert',
  'compress',
  'resize',
  'upscale',
  'removebg',
  'generate',
  'tools',
  'completed',
  'settings',
  'addfile',
  'folder',
  'play',
  'stop',
  'retry',
  'close',
  'check',
  'warning',
  'clock',
  'sync',
  'chev-r',
  'chev-d',
  'trash',
  'cleardone',
  'eye',
  'info',
  'arrow',
  'sidebar',
  'anvil',
  'image',
  'pdf',
  'text',
  'merge',
  'split',
  'burst',
  'pull',
  'archive',
  'video',
  'audio',
  'doc',
  'unpack',
  'topdf',
  'tocbz',
  'edit',
  'grip',
  'dots',
  'view-details',
  'view-tiles',
  'view-medium',
  'view-large',
  'view-xl',
  'mouse'
] as const

export type IconName = (typeof ICON_NAMES)[number]
